name: Deploy to Azure Web App

on:
  push:
    branches:
      - master  # ou 'master', dependendo da sua branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'  # ou a versão que você está usando

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: helloapi  # nome do seu App Service
        slot-name: production
        publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
        package: ./publish
